apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw20-gitops-app
  labels:
    app: hw20-gitops-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hw20-gitops-app
  template:
    metadata:
      labels:
        app: hw20-gitops-app
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
