apiVersion: v1
kind: ConfigMap

metadata:
  name: app-config

data:
  LOG_LEVEL: info
  APP_PORT: "8080"
  APP_MODE: production

---
apiVersion: v1
kind: Secret

metadata:
  name: app-db-secret

type: Opaque

stringData:
  password: change-me-in-real-life
